# The following redirect is intended for use with most SPAs that handle
# routing internally.
# [[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  # TODO: I think this now is superfluous. -> it is NOT. Is it in the index.html not necessary anymore or do we need both?
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://accounts.google.com https://www.gstatic.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https: data:; connect-src 'self' https:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none';"
