// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHUlqhjrXSAJfrOFk5z7Ig1AHmV54KcKY',
    appId: '1:99195584485:web:69e873ae5d5d6601d7390c',
    messagingSenderId: '99195584485',
    projectId: 'worktime-om',
    authDomain: 'worktime-om.firebaseapp.com',
    storageBucket: 'worktime-om.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnjnb9WlPeuzUMEWoHv7LX0bUukHdimL4',
    appId: '1:99195584485:android:85ae81321c43972dd7390c',
    messagingSenderId: '99195584485',
    projectId: 'worktime-om',
    storageBucket: 'worktime-om.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4HMNVHKQGTf2tQDIi42mXaaBiKzN0dXQ',
    appId: '1:99195584485:ios:00441a40e53d19dcd7390c',
    messagingSenderId: '99195584485',
    projectId: 'worktime-om',
    storageBucket: 'worktime-om.appspot.com',
    iosClientId: '99195584485-h664edkhkprqftte2bmr6untl6puchig.apps.googleusercontent.com',
    iosBundleId: 'com.example.workTimeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4HMNVHKQGTf2tQDIi42mXaaBiKzN0dXQ',
    appId: '1:99195584485:ios:00441a40e53d19dcd7390c',
    messagingSenderId: '99195584485',
    projectId: 'worktime-om',
    storageBucket: 'worktime-om.appspot.com',
    iosClientId: '99195584485-h664edkhkprqftte2bmr6untl6puchig.apps.googleusercontent.com',
    iosBundleId: 'com.example.workTimeApp',
  );
}
